# This is a basic workflow to help you get started with Actions

name: Manual input workflow

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # inputs the workflow accept
      inputs:
        name:
          # Friendly description to be shown in the UI instead of name
          description: 'person to greet'
          default: 'Anjan'
          required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: send greetings
      run: echo "Hello ${{github.event.inputs.name}}"
